---
- name: Include distro-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: Run distro-specific pre tasks (CentOS)
  block:
    - name: Use epel
      ansible.builtin.package:
        name: epel-release
        state: present
  when: ansible_distribution == "CentOS"

- name: Install base system packages
  ansible.builtin.package:
    name: "{{ packages }}"

- name: Increase inotify limit
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    sysctl_file: /etc/sysctl.d/50-inotify.conf
    reload: true

- name: Run distro-specific post tasks (CentOS)
  block:
    - name: Make sure firewalld is started
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Whitelist services
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - ssh
        - http
        - https

    - name: Disable selinux  # sorry
      ansible.posix.selinux:
        state: disabled
  when: ansible_distribution == "CentOS"

- name: Run distro-specific post tasks (Debian)
  block:
    - name: Make sure ufw is started
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: true

    - name: Blacklist everything incoming
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny

    - name: Whitelist services
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 80
        - 443
  when: ansible_distribution == "Debian"
